# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/tangjiaxin188"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "email"
    name       = "Email"
    url        = "send@email.tangjiaxin.top"

    [social.params]
        icon = "mail"

[[social]]
    identifier = "bilibili"
    name       = "bilibili"
    url        = "https://space.bilibili.com/1308291832"

    [social.params]
        icon = "bilibili"
